### ISSUE TITLE
Use of atomics

### ISSUE THREAD

**Issue by Ciekce** [holoskii/RayTracing#3]
In several places atomics are incremented with code like this:
```cpp
finishedPixels.store(finishedPixels.load() + 1);
```
This is not atomic, it's three separate statements (read, modify, write). Consider what happens if you have two threads modifying the same variable:

1. Thread 1 calls `finishedPixels.load()` and reads (for example) the value 2
2. Thread 2 also calls `finishedPixels.load()` and also reads 2
3. Thread 1 increments the value to 3 and calls `finishedPixels.store(3)`
4. Thread 2 increments the value to 3 and *also calls `finishedPixels.store(3)`*.

The value is now 3 instead of the expected 4, just as if you had used a plain non-atomic variable - this is what atomic operations exist to avoid.

`std::atomic` overloads the `++` and `--` operators, so you can increment/decrement your values as one unsplittable (-> atomic) operation.

**Comment by holoskii** [comment]
Fixed it, thanks!
